version: '3'

services:
  shorty:
    build: .
    command: "bin/shorty start"
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/shorty_dev"
      SECRET_KEY_BASE: "2Io2EdjezXEyQnsYoQQCcdxuTD7nXE10AHMlu6Xh8uXr8F8nMrYlTNCO8JpgY7EY"
      ENDPOINT_URL: "http://localhost:4000"
      LISTENER_PORT: 4000

  mix:
    build:
      context: .
      target: builder
    entrypoint: "mix"
    command: "help"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/shorty_dev"

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
