version: 2.1

jobs:
  build:
    docker:
      - image: elixir:1.11-alpine
        environment:
          MIX_ENV: test
      - image: postgres:13-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix credo
      - run: mix test
